# Generated by Django 5.1.4 on 2025-01-01 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='posts_comme_user_id_5151d7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='posts_comme_post_id_06cfd5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['timestamp'], name='posts_comme_timesta_b7b9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender'], name='posts_direc_sender__99a823_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['recipient'], name='posts_direc_recipie_ceb59b_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['is_read'], name='posts_direc_is_read_f1d27f_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['timestamp'], name='posts_direc_timesta_f25498_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='posts_like_user_id_842d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post'], name='posts_like_post_id_db9889_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['timestamp'], name='posts_like_timesta_14f027_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='posts_notif_user_id_1d818e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender'], name='posts_notif_sender__03e1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['post'], name='posts_notif_post_id_172149_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='posts_notif_is_read_47d55d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['timestamp'], name='posts_notif_timesta_654b15_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='posts_post_author__19d68b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['timestamp'], name='posts_post_timesta_80b5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['shared_post'], name='posts_post_shared__358e2a_idx'),
        ),
    ]
