# Generated by Django 5.1.4 on 2025-01-03 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='users_follo_followe_3a2483_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='users_follo_followi_e01def_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='users_profi_user_id_783607_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['bio'], name='users_profi_bio_0ca8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['profile_picture'], name='users_profi_profile_47bee2_idx'),
        ),
    ]
